name: Nix actions

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  nix-flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run checks
        run: nix flake check -L
